"""populate feature table

Revision ID: 7df3f3df788f
Revises: defbe4ea1e51
Create Date: 2026-06-04 08:56:02.581717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7df3f3df788f'
down_revision: Union[str, Sequence[str], None] = 'defbe4ea1e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Define table structure for the migration context
    feature_table = sa.table(
        "features",
        sa.column("id", sa.Integer),
        sa.column("name", ENUM("diarization", "emotion", "stt", name="featurename", create_type=False)),
        sa.column("order_idx", sa.Integer),
    )

    # Insert feature data for this migration so the table is populated
    op.bulk_insert(
        feature_table,
        [
            {"name": "diarization", "order_idx": 1},
            {"name": "emotion", "order_idx": 2},
            {"name": "stt", "order_idx": 3},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
