"""initial migration features

Revision ID: defbe4ea1e51
Revises: 
Create Date: 2026-06-04 08:40:28.291543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'defbe4ea1e51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('diarization', 'stt', 'emotion', name='featurename'), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_name'), 'features', ['name'], unique=True)
    op.create_index(op.f('ix_features_order_idx'), 'features', ['order_idx'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('callback_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_task_uuid'), 'tasks', ['task_uuid'], unique=True)
    op.create_table('features_in_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'PROCESSING', 'READY', 'FAILED', name='featurestatus'), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('features_in_task')
    op.drop_index(op.f('ix_tasks_task_uuid'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_features_order_idx'), table_name='features')
    op.drop_index(op.f('ix_features_name'), table_name='features')
    op.drop_table('features')
    # ### end Alembic commands ###
